### ISSUE TITLE
Review Problem Statement

### ISSUE THREAD

**Issue by joedf** [joedf/CAS741_w23#1]
Hi Dr. Smith!

Here is my first version of my [ProblemStatement.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf). 😬 

I've made my current code public here: https://github.com/joedf/ImgBeamer
I will likely have to improve or re-implement some parts, but I was thinking of adding it as a submodule to this repository instead of copying it over. This way I can preserve the commit history and branches I have on there. Would that be okay?

**Comment by smiths** [comment]
@joedf, can you refresh my memory on submodules in repositories.  I definitely like the idea of you keeping the history of your current project.

- There is often spaces missing after periods, like in the second paragraph there should be a space after [1]
- is the output just the two images?  Are there any scalar metrics that represent the under or oversampling?  I don't know the domain, but I feel like there should be some kind of number to represent the quality of the image?
- is web-based a constraint, or is it something that can be derived as a design decision from the nonfunctional requirements?  If it isn't a constraint, we shouldn't mention it prematurely to the design decision.

I'll approve the project, but it would be good if you could answer my above questions, and fix the spacing issue.

**Comment by joedf** [comment]
@smiths
Thanks! I must have missed those spaces when I fiddling around line length and hard wrapping. LaTeX is pretty cool!

I haven't used submodules too much, but essentially they are like a symbolic link to another repository at a specific commit (but can be updated). When cloning this repository, the files from submodules will not be there unless we run `git submodule init` and `git submodule update` to pull all the source files. Or maybe just a url link would suffice?

As the output, yes it would mainly be just the two images (considered as the results), but there are intermediate steps that are drawn and displayed to the user as well. I haven't looked at metrics yet, but you've sparked some ideas in my head! 😄

Maybe some kind of modified cross-correlation technique between the output images (from different parameters) and the original/input image. I found [this paper](https://ieeexplore.ieee.org/document/7872602) that attempts to estimate signal-to-noise ratio of SEM images using linear regression. This also reminds me of a mini-survey I saw at work where people had to choose the "best" between many versions of an image.

I also found [this neat paper](https://www.researchgate.net/publication/257812687_Improving_Scanning_Electron_Microscope_Resolution_for_Near_Planar_Samples_Through_the_Use_of_Image_Restoration) on SEM (over/exact/under)sampling.

This does raise a good point; Image quality could be measured objectively or subjectively. I'd say an image that is blurrier but does not miss any features is more valuable scientifically, then an image that looks sharper but misses some details.

I've removed the mention of web-based. Makes sense, I was hesitant and unclear to keep that in. 

Let me know if there's anything else. Thanks, this is helpful!

**Comment by smiths** [comment]
Thanks for the information @joedf on sub-modules.  Now that you remind me, I had a project where we thought about using that infrastructure, but in the end it felt like it wasn't justified.  I think we just went with a simple pointer (link) to the other module.  From the point of view of CAS 741, it doesn't matter to me what you decide to do, as long as you give explicit credit to your previous work.  Whatever you think will be most useful to you, in the long run, is fine with me.

For comparing images, one metric I've seen with image segmentation is the [Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient).  If you have a ground truth, which I seem to remember reading that you have, comparing to the ground truth via the Dice score, or some other similarity metric, might make sense.

**Comment by smiths** [comment]
@joedf when you make a change to address an issue, it is nice if you can point to that change.  GitHub facilitates that by allowing you to easily point to a specific commit, just by providing the commit hash.  For instance, you can say that commit 72bb203ca1d368019b977dfe1c92403c8db607ab removes the design constraint of requiring a web interface from the outset.

Since the problem statement is approved, I'll close this issue.

**Comment by joedf** [comment]
Great, thanks! I'll have a look at the Dice coefficient.
