### ISSUE TITLE
Is there anything you could mention about the “optimal spot-to-pixel-size ratio”? Perhaps with Examples?

### ISSUE THREAD

**Issue by balacij** [joedf/CAS741_w23#16]
Are there any qualitative and/or quantitative metrics that users should think about when checking if images are better/worse quality after processing? If so, do you think you could mention some? Right now, the idea of an “optimal spot-to-pixel-size ratio” is a bit difficult to understand.

**Comment by joedf** [comment]
Thanks. You're right. I feel that I didn't explain as much as I'd like for the "optimal" ratio. Hopefully, this is now much clearer with the new figures I've added.
