### ISSUE TITLE
Review SRS

### ISSUE THREAD

**Issue by joedf** [joedf/CAS741_w23#2]
Hello Dr. Smith!

Not sure if I did this right. I made some corrections with the suggestions from class. I struggled with the traceability among other things, but I'm sure I'll learn and understand later on.
  
[SRS.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/SRS/SRS.pdf)

Hopefully, I didn't forget or miss anything.

**Comment by smiths** [comment]
Sounds good @joedf.  I look forward to reading it over.  :smile:

**Comment by joedf** [comment]
<strike>@zehongwong</strike> @KarenKarenWang
I have sent collaborators invites to you for this repo. Please have a look when you have time

I've made separate issues for each of you and will assign the case once you have collaborator access.
<strike>Zehong: https://github.com/joedf/CAS741_w23/issues/3</strike>
Karen: https://github.com/joedf/CAS741_w23/issues/4

@balacij I've sent you a collaborator invite! 👍

**Comment by balacij** [comment]
Disclaimer: I'm not familiar much with image processing on computers, so you should take all of my advice with a grain of salt.

I'm going to post my tickets now. I enjoyed reading your SRS, and I look forward to seeing what you build in the future :smile: 

EDIT: I've posted my feedback now.

**Comment by smiths** [comment]
I've finished my review of the SRS.  The marked-up version is in d607e6a.
