### ISSUE TITLE
IM2 looks important, but I'm not sure how it's meant to be used. How is it calculated?

### ISSUE THREAD

**Issue by balacij** [joedf/CAS741_w23#22]
* I was a bit surprised when I saw IM2, I didn't expect that there would be a numeric metric. Do you think you could make it more prominent in the earlier parts?
* It also seems to be missing an output symbol.
* Finally, do you think you can add a mathematical description of it?

**Comment by joedf** [comment]
Good point, I don't have an output symbol. 
@smiths You asked about this as well....

I wasn't sure what metric to use at the time. I was still searching for one to use, so I tried to stay abstract. I think I may stick to something relatively simple like a Root Mean Square Error based metric. I ran some tests with different existing metrics (UQI, MSE, RMSE, PSNR, SSIM, VIFP, SSC, MSSSIM,  in python and javascript. I will likely show these tomorrow. Not perfect, but reasonable... Maybe this will make more sense when I demo it. Looking forward to the input.

I also tried some cross-correlation, but that was too heavy and not particularly useful for me.

**Comment by smiths** [comment]
@joedf that is great that you are using abstraction, but this is a better place for "faking it."  Abstraction isn't a way to put off decisions.  It is a way for the decisions to be more general.  In the case of your metric, it is easiest to pick one (or more) for the documentation.  If you later change your mind, you can just change the documentation to make it look like you always intended to use whatever metric you later decide to use.  :smile:

**Comment by joedf** [comment]
Thanks, in that case I'll just pick one and put it in. This helps me with my VnV plan as well. I'll just have to use some rough numbers for now, since it is also a bit abstract and vague for that part...
