### ISSUE TITLE
Review VnV Plan

### ISSUE THREAD

**Issue by joedf** [joedf/CAS741_w23#25]
Hello @smiths !

I have done what I can for the VnV plan. I've spent the better part of a day on this. 😅 
[VnVPlan.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/VnVPlan/VnVPlan.pdf)

Again, I don't think I fully understood everything, but I shall learn and "fake it" as we say. 😉 
Looking forward to your feedback.

**Comment by smiths** [comment]
Sounds good @joedf.

**Comment by samm82** [comment]
Finished!

**Comment by joedf** [comment]
@samm82 Wow, so fast! ahah

**Comment by smiths** [comment]
Feedback is in the attached marked-up pdf.

[VnVPlan_Fdbck.pdf](https://github.com/joedf/CAS741_w23/files/10904042/VnVPlan_Fdbck.pdf)
