### ISSUE TITLE
VnV Plan Review: Revision History

### ISSUE THREAD

**Issue by samm82** [joedf/CAS741_w23#27]
Your revision history should be more detailed (ideally it should group your git commits into meaningful "chunks"). (Also it looks like you left in the default second row!)
_Side note: your commit messages should be more description than "progress on vnv" - what progress was made? Summarize it!_

**Comment by joedf** [comment]
Yeah agreed... I think a lot of it was half written sentences and paragraphs in different sections, so I didn't have any clear. I just have the constant fear that I need to save and commit constantly... 😅

I spent around 11hrs straight on this Friday and brain was fried... :b 
I did the same with the SRS, where I only update the changelog once I implemented changes from reviewers...

I shall try to be more descriptive from now on.
