### ISSUE TITLE
VnV Plan Review: Ground truth reference?

### ISSUE THREAD

**Issue by samm82** [joedf/CAS741_w23#32]
The last sentence of the Implementation Verification Plan says "As a control for the image metrics, they will be calculated using the same image as the ground truth reference to rule out any baseline or unexpected factors in the implementations themselves." I am confused as to what this means: what is the "ground truth reference?" What does it mean to "rule out any baseline ... factors"?

**Comment by joedf** [comment]
I reworded, yeah wasn't very clear.  I just meant to compare the ground truth image to itself to see if it gets the perfect/expected scores.
