### ISSUE TITLE
VnV Plan Review: Make tests more specific

### ISSUE THREAD

**Issue by samm82** [joedf/CAS741_w23#36]
Similarly to #31, some tests are too vague. Some examples of details to think about:

- [x] What are the specific inputs to these tests? T7 and T8 give a range of possible values, and T2 allows for one to not even be provided! You should pick specific values/images for these tests or outline the procedure for obtaining them. If necessary, create multiple tests for multiple inputs!
- [x] Similarly, how will these tests be performed? T3 allow for the test to be performed "by scrolling in the visual spot shape UI or by number input in the GUI."
- [x] Ideally, you would provide the exact images that would be passed to the program for testing. If that is not possible at this stage, at least more specific information about how images should be transformed should be given:
   - [x] In T5, how should "the resulting image resolution ... grow or shrink according to the pixel size given"?
   - [x] In T7-9, what does "somewhat sharp" or "somewhat blurry" mean?
- [x] How many warnings does "little to no warnings" mean in T12? How much setup is "little to no setup" in T14? Does this setup include installation?

**Comment by joedf** [comment]
Thanks for the thorough input! Yes, I haven't fully decided on a specific metric, so I was unsure of the actual values to use or what is considered a "good" score yet.... T2 was wrong, it should be a button click on "Export". I shall update this once I have some better numbers.

For the second and third points, I honestly don't know what to do. I have no idea how to specify visual / UI-based tests... ☹️ Do you have a suggestion? Or if provide image examples? I have some in the SRS I could point to...

For the last point, I've put in some arbitrary numbers for now, hope that works. 😬

**Comment by samm82** [comment]
> Similarly, how will these tests be performed? T3 allow for the test to be performed "by scrolling in the visual spot shape UI or by number input in the GUI."

The main issue here is that there are two ways for test to be performed. "Scrolling in the visual spot shape UI" tests that component, and doing so "by number input in the GUI" tests another. These tests will be more specific once you start making design decisions (although it seems like you are already there/rapidly approaching it! In that case, UI screenshots seems like a good way to specify them).

>  In T5, how should "the resulting image resolution ... grow or shrink according to the pixel size given"?

What is the desired relationship between the resolution and the pixel size? (I'm sure this is clear from the SRS/other documents, but it is not immediately apparent from the VnV alone.)

> In T7-9, what does "somewhat sharp" or "somewhat blurry" mean?

I have no idea how I would make this more specific. "Blurry" and "sharp" already have some level of ambiguity to them, which is amplified by the qualifier "somewhat"! Some way to quantify blurriness/sharpness would be ideal, but I'm not sure if that's feasible.

> For the last point, I've put in some arbitrary numbers for now, hope that works. 😬

Love to see a faked design process! 😁

**Comment by joedf** [comment]
LOL. thanks, this is helpful.
