### ISSUE TITLE
MG+MIS Review - Peers

### ISSUE THREAD

**Issue by joedf** [joedf/CAS741_w23#38]
@KarenKarenWang @LesleyWheat

Hi there,
I got an extension to complete my MG/MIS for this Sunday night. Hopefully, I should be done sooner or later...

**Comment by joedf** [comment]
Here they are 😅:

- [MG.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/Design/MG/MG.pdf)
- [MIS.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/Design/MIS/MIS.pdf)

**Comment by LesleyWheat** [comment]
Done

**Comment by joedf** [comment]
Great, thank you both!
