### ISSUE TITLE
MG+MIS Review

### ISSUE THREAD

**Issue by joedf** [joedf/CAS741_w23#39]
Hi Dr. Smith,

This was a tough one. Here's goes for my best attempt 😅
- [MG.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/Design/MG/MG.pdf)
- [MIS.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/Design/MIS/MIS.pdf)

Cheers!

**Comment by smiths** [comment]
@joedf my feedback is attached.

[MG_Fdbck.pdf](https://github.com/joedf/CAS741_w23/files/11212323/MG_Fdbck.pdf)
[MIS_Fdbck.pdf](https://github.com/joedf/CAS741_w23/files/11212324/MIS_Fdbck.pdf)
