### ISSUE TITLE
MG: AC12

### ISSUE THREAD

**Issue by LesleyWheat** [joedf/CAS741_w23#40]
> AC12: The implementation of graphical user interface.

What do you mean by "implementation" here? Like it would look the same but be programmed in a different language? Or be rendered using a different library? Or do you mean changes to the requirements of the GUI (display different things, etc)? "Implementation" is very vague.

**Comment by joedf** [comment]
Good point, I'll add further detail specifying that this may entail a different language or UI/UX design.
