### ISSUE TITLE
MG: UC1

### ISSUE THREAD

**Issue by LesleyWheat** [joedf/CAS741_w23#41]
> UC1: Input/Output devices (Input: File and/or Keyboard, Output: File, Memory, and/or Screen).

Thinks seems like a strange unlikely change for your software? It seems like the software could run on a laptop or a tablet (which doesn't have a keyboard).

**Comment by joedf** [comment]
I see... I think kept that verbatim from the template, but yes it could run on device without a physical keyboard.
... but it could have an on-screen keyboard, mostly meant that there's number/text entry.
I'll explicitly mention on-screen keyboard.
