### ISSUE TITLE
MG: ...returns an update function (reference/pointer)...

### ISSUE THREAD

**Issue by LesleyWheat** [joedf/CAS741_w23#43]
This is used in many modules, I do not think you need to be so specific as to mention pointers. Maybe a more general statement like "Provides functionality to update the drawing/image upon request"?

**Comment by joedf** [comment]
Perhaps I am being too specific... @smiths Thoughts? is it okay to mention function pointers?

**Comment by smiths** [comment]
@joedf I prefer the MIS to be more abstract than to mention function pointers.  The MIS is a mathematical document.  If you want to pass a function as a parameter, than you can just pass the function as a function.  If you are familiar with functional programming, you can think of the MIS language as allowing for functional programming.  Functions are treated as a [first-class data](https://en.wikipedia.org/wiki/First-class_function).  Functions can be passed as arguments to other functions, and returned by functions.

**Comment by joedf** [comment]
Thanks, I think I am bleeding in my experience from C. I looked it up and apparent functions are indeed considered "first-class objects" in javascript. I shall update the docs to just say "function". 👍
