### ISSUE TITLE
MG: Minor points

### ISSUE THREAD

**Issue by LesleyWheat** [joedf/CAS741_w23#45]
p2
> AC10: The implementation of rendering, compositing, clipping, or blending operations (e.g., “Bit BLT”).

BLT is not in acronyms.

> AC7: How the overall control of the calculations are orchestrated.

Unclear sentence.

> AC8: The display of information on the visualizations and resulting images.

Unclear sentence.

p3
> UC6: The software must be able to display a live visualization to the user of the effects of changing the imaging parameters

Run on sentence

![image](https://user-images.githubusercontent.com/29044132/226691122-7297cba1-06a0-4959-a6f3-27b8eb232953.png)
I like this. I think the table might be cutting into the right page margin.

p6
> Secrets: The algorithm for coordinating the running of the program.

Awkward sentence.

> Secrets: The format, structure, verification of the input ground truth image data.

Missing "and".

> Secrets: The format and current values of the input imaging parameters (number of rows and columns for the rasterization grid and magnification) data.
> Services: Gets and provides the parameters values.

Are the values a secret if they are provided to other modules?

p 10
> Secrets: The number of drawing stages / canvases and the references to them, the update and redraw events, drawing rates, and the connection to rendering (M20).

I think this is overly specific again. What about "The images currently displayed and the display information associated/required with/for each one (drawing rate, etc)"?

> Services: Initializes the drawing stages, provides methods to manipulate them and to attach events, manages the image rendering and drawing, and holds and manages the update function references for each drawing stage.

Overly specific? This could be shorter "Initalizes and manages the display." maybe "initalizes and manages the display objects. Is reponsible for image rendering, image updating, etc).

> Secrets: The HTML DOM Manipulation; CSS rules; user interaction event handling; user input controls, states, and data formats (such as text-boxes, buttons, file dialogs); along with the layout, styles, colors, and sizing.

I'm not sure if we're supposed to be that specific with the languages (imo it's fine though). I don't know if those semicolons are gramatically correct.

>Services: Sets up a visual interface for the user to see and interact with, handles user and GUI control events, updates the visual elements representing the state of the application, and sends messages back to the application control (M2) to update the application state accordingly.

This one is nice.

p 11
> Secrets: The algorithm, criteria, and validations for processing and comparing two images.

"validations" to "validation algorithm/calculation"?

> Services: Compares two images (ideally one - a reference or ground truth image, and the other - an image to compare to) and produces a score on the similarity or quality of the compared image with respect to reference image.

I would rewrite as: "(ideally, one should be a reference or ground truth image and the other should be ...)"

**Comment by joedf** [comment]
Thanks! commit: 66910438a44b869511020c8419dcd2e50f2a2769
