### ISSUE TITLE
MIS: Minor points

### ISSUE THREAD

**Issue by LesleyWheat** [joedf/CAS741_w23#50]
p8
> 7.4.5 Local Functions
> doUpdate(), updateInfoDisplay(), and doExport() as described above.

Functions aren't local if they can be accessed by other modules. These should probably be included as exported access programs.

p13
For 10.2 Uses, maybe just use bullet points instead of numbered points (as there doesn't seem to be an order).

p14
> 10.4.2 Environment Variables
> Display/Canvas controls as provided by the GUI Module (M18).

I'm not sure about this, if another module is providing a variable then is it an environment variable here? Would it just be listed in that module?

p25
> Mouse events handled by Konva for shape node-editing / “transformers”.

Maybe just say "None" if you aren't writing any.

p28
> drawSpotSignal (M??)

**Comment by joedf** [comment]
Thanks!

p8: those are not accessed by other modules. The `doUpdate()` just shares the same name as with some of the other modules 😅... and the others are essentially the event handlers on the GUI.

p13: it is a bit weird isn't it.... but I reference to it from the "2 to 10" in the table right below.
