### ISSUE TITLE
MG

### ISSUE THREAD

**Issue by KarenKarenWang** [joedf/CAS741_w23#51]
In the section "4 Anticipated and Unlikely Changes," there is a small typo where "adapted" should be "adopted": "The approach adapted here is called design for change."
2.	In the same section, "The module design should be as general as possible." May changed to "The module design should be as flexible as possible."
3.	In the section 7, the explanation for the "Implemented By" title should have consistent capitalization and formatting for each entry (e.g., "OS," "WebBrowser," "jQuery," "CanvasAPI," "Konva," and "ImgBeamer").

**Comment by joedf** [comment]
1. Oh good catch, thanks! Maybe mention it to Dr. Smith, it's from the template text.
2. also, from the template, and I fear it might change the meaning Dr. smith meant... maybe flexible is better? @smiths 
3. I am not sure what you mean? You mean "jQuery"? It is always written with a lowercase: https://jquery.com/

**Comment by smiths** [comment]
@joedf the intended wording is general (not flexible).  General is one of our quality criteria for a good design.  The terminology comes from the [Hoffman and Strooper](https://gitlab.cas.mcmaster.ca/smiths/pub/-/blob/master/HoffmanAndStrooper1995.pdf) text.

**Comment by joedf** [comment]
Thanks!
