### ISSUE TITLE
MG cont

### ISSUE THREAD

**Issue by KarenKarenWang** [joedf/CAS741_w23#52]
1. In the "Implemented By" field for "7.1 Hardware Hiding Modules (M1)" and "7.2 Behaviour-Hiding Module", may think about using a more specific implementation, like an operating system or software name, rather than just "OS" or leave it blank.
2.	In the "Implemented By" fields, when multiple implementations are mentioned, they should be separated by commas and a space. For example, in "7.2.2 Ground Truth Image Input (M3)", it should be "Implemented By: CanvasAPI, ImgBeamer" instead of "Implemented By: CanvasAPI and ImgBeamer".
3.	In the "7.3.3 Drawing Stage / Canvas Module (M19)" section, the last sentence should end with a period instead of a comma.
4.	Hyphens and spaces are inconsistent in the module names. For example, "Behaviour-Hiding Module" and "Hardware Hiding Modules" should have a consistent format, such as "Behaviour-Hiding Modules".
5.	Ensure consistent capitalization in module names. For example, "7.3.4 Image Rendering (M20)" has "Image Rendering" capitalized, while "7.2.14 Resulting Subregion Visualization (M15)" has "Resulting" capitalized, but "subregion" in lowercase.

**Comment by joedf** [comment]
1. This is from the template. I will leave it as is for now.
2. I am unsure about this. I think is just styling.
3. I don't see the comma at the end of the sentence... ???
4. Fixed. 👍 
5. no? In the example you provided, "subregion" is capitalized already... I double-checked that everything is title-case...

**Comment by joedf** [comment]
Closing for now...
