### ISSUE TITLE
MIS

### ISSUE THREAD

**Issue by KarenKarenWang** [joedf/CAS741_w23#53]
1. There is inconsistent spacing between sections and subsections throughout the document. Ensure consistent spacing for better readability.

2.	In various sections, ensure that proper indentation is used for better readability and consistency.

3.	In section "7 MIS of Graphical User Interface (GUI)", under "7.4.4 Access Routine Semantics", the author states, "I am not sure what transition means...". This comment should be replaced with the appropriate description, or "transition" should be clarified earlier in the document.

4.	The document has author comments in square brackets ([]). These comments should be removed from the final version of the document.

5.	Typographical errors:

-    Section 9.4.3: "The output location is a valid writable and accessible." should be "The output location is valid, writable, and accessible."
- 	Section 11.4.4, in the "init()" entry: "container is the control or location given by the GUI Module (M18)." should be "container is the control or location given by the GUI Module (M18)."

6.	In section 18.1, there's a missing module number for "drawSpotSignal":

7.	Consistent punctuation and capitalization: Some section titles end with a period, while others don't. For consistency, either remove the period from all section titles or add a period to those that don't have one.

8.	In the "20.2 Uses" section, consider listing the modules as bullet points for improved readability:
•	Rendering Module (M20)
•	DrawingStage Module (M19)

**Comment by joedf** [comment]
5b. (on section 11.4.4) there's no difference between the two examples you shared.... ?
7. I check every title and subsection title... no periods anywhere?

**Comment by joedf** [comment]
Closing for now...
