### ISSUE TITLE
Final Documentation Submission for Review

### ISSUE THREAD

**Issue by joedf** [joedf/CAS741_w23#54]
Here's all the final documentation. Links are provided below for your convenience :)

- [ProblemStatement.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf)
- [SRS.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/SRS/SRS.pdf)
- [VnVPlan.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/VnVPlan/VnVPlan.pdf)
- [MG.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/Design/MG/MG.pdf)
- [MIS.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/Design/MIS/MIS.pdf)
- [VnVReport.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/VnVReport/VnVReport.pdf)
- [Reflection.pdf](https://github.com/joedf/CAS741_w23/blob/main/docs/Reflection/Reflection.pdf)

**Comment by smiths** [comment]
Great!  Thank you @joedf.  I look forward to reviewing your final code and documentation.

**Comment by JoseMRodriguezM** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
cjh0613, @steinbrueckri, @my3157, @G0blinK, @jessebraham, @pengwk, @spoof, @partyzanex, @wenhhh, @heartwilltell, @omarryhan, @DrowningToast, @stefan-kolev, @cgaolei, @irvinhomem, @jwcha, @hautph, @fam4r, @akaped, @namKolo
