### ISSUE TITLE
Bibliography 

### ISSUE THREAD

**Issue by KarenKarenWang** [joedf/CAS741_w23#6]
I am not sure if this will be a problem, it just my professor from other before told us it better not put Wikipedia as reference.

**Comment by joedf** [comment]
Thanks. Agreed, but the documentation is somewhat lacking... I did finally find one good reference to explain the algorithm... It's a very old technique from the 1980s and is now a low level operation on GPUs. I left the wiki ref alongside it for further reading as it contains some images explaining the method.
